[package]
name = "wirechaos-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true, features = ["net", "io-util", "time", "sync"] }
tracing.workspace = true
serde.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
thiserror.workspace = true
bytes.workspace = true