[package]
name = "wirechaos-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true, features = ["net", "io-util", "time", "sync"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
serde.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
thiserror.workspace = true
bytes.workspace = true
tokio-rustls.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "net", "io-util"] }
rcgen = "0.13"