[package]
name = "wirechaos"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wirechaos-core = { path = "../wirechaos-core" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true